import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./(common)/components/header";
import Footer from "./(common)/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CyberSapient",
  description: "Generated by sajeer k",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <Footer/>
    </html>
  );
}
